# Minimal ubi9-micro image. Adds a marker file; nothing removed.
FROM registry.access.redhat.com/ubi9-micro@sha256:7a0454cbd9bd847e8f6a63b6f0254a6efbeb6e0ed71a5d824a4f6cccbe626650

RUN echo "hello" > /hello.txt