# Minimal ubi9-micro image with shell + common utils removed (no package
# manager is available in ubi9-micro, so binaries are removed directly).
# All removals must happen in this single RUN: deleting /bin/sh would break any
# subsequent RUN instruction.
FROM registry.access.redhat.com/ubi9-micro@sha256:7a0454cbd9bd847e8f6a63b6f0254a6efbeb6e0ed71a5d824a4f6cccbe626650

RUN rm -f /usr/bin/bash /usr/bin/sh /usr/bin/less /usr/bin/more /usr/bin/cat