name: Build and Push 'standard' containers with podman

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'

env:
  REGISTRY_USER: rh-ee-chbutler
  IMAGE_REGISTRY: quay.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: ['coredumps']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}

    - name: Log in to registry.redhat.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: registry.redhat.io

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ matrix.containers }}
        tags: latest 
        containerfiles: |
         ./standard/${{ matrix.containers }}/Containerfile


    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ matrix.containers }}
        tags: latest
        registry: quay.io/${{ env.REGISTRY_USER }}